### ISSUE TITLE
Multiple filters

### ISSUE THREAD

**Issue by Huc91** [sensorario/queryfilters#10]
```javascript
      q.applyFilter([{
       field: '_embedded.foo.bar',
       value: 'foo'
      },
      {
       field: '_embedded.foo.bar',
       value: 'foo'
      },
      ]);
      const TEST_STRING = q.getQueryString();
      console.log(TEST_STRING);
```
I tried to add multiple filters by passing an array with objects to the `applyFilter`.
Returns this error, I'm using Vue.js
```
[Vue warn]: Error in created hook: "TypeError: filter.field is undefined"
```
so this error is more Vue specific. It means that he found an error in the created() hook that is Vue specific. It's where I'm currently testing queryfilters.
```
TypeError: "filter.field is undefined"
```
I think this is the error

**Comment by sensorario** [comment]
closed by #11
